version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - walnuts1018
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - walnuts1018
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - walnuts1018
  - package-ecosystem: docker
    directories:
      - "/backend"
      - "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - walnuts1018
