version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/apiserver"
      - "/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directories:
      - "/apiserver"
    schedule:
      interval: "weekly"
