FROM node:lts-bookworm-slim
WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/yarn,sharing=locked \
  --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=yarn.lock,target=yarn.lock \
  yarn install --frozen-lockfile

COPY . .

CMD ["yarn", "dev"]
