services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    working_dir: /app
    tty: true
    volumes:
      - source: ./backend
        target: /app
        type: bind
      - target: /go/pkg/mod
        type: tmpfs
      - target: /root/.cache/go-build
        type: tmpfs
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug
      SERVER_ENDPOINT: "https://mucaron.local.walnuts.dev"
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DATABASE: mucaron
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_SSLMODE: disable
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
      MinIOUseSSL: "true"
      REDIS_HOST: redis
      REDIS_PASSWORD: "redispassword"
      SESSION_SECRET: "mock-session-secret-----"
      LOG_TYPE: "text"
      MINIO_PUBLIC_ENDPOINT: "https://minio.local.walnuts.dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres
      - minio
      - redis
  # Docker for WindowsでHot Reloadが動かないので、フロントエンドはローカルで動かす
  # frontend:
  #   image: node:20
  #   working_dir: /app
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.local
  #   ports:
  #     - "3000:3000"
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./frontend/src
  #         target: /app/src
  #       - action: rebuild
  #         path: ./frontend/package.json

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./psql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  minio:
    image: minio/minio
    ports:
      - 9001:9001
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
    command: server /export --console-address ":9001"
  redis:
    image: bitnami/redis:7.4
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redispassword"
    volumes:
      - redis_data:/bitnami/redis/data
  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - source: ./nginx
        target: /etc/nginx/conf.d
        type: bind
      - source: ./certs
        target: /etc/certs
        type: bind
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - backend
      - minio

networks:
  default: {}

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  minio_config:
    driver: local
  redis_data:
    driver: local
