services:
  backend:
    image: golang:1.22-bookworm
    working_dir: /app
    command: go run air-verse/air
    volumes:
      - source: ./backend
        target: /app
        type: bind
    ports:
      - "8080:8080"
    environment:
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DATABASE: mucaron
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_SSLMODE: disable
      PROXY_PASSWORD: proxy_password
    depends_on:
      - postgres
  frontend:
    image: node:20
    working_dir: /app
    command: >
      bash -c "npm install && npm run dev"
    volumes:
      - source: ./frontend
        target: /app
        type: bind
    ports:
      - "3000:3000"
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
      - ./psql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  minio:
    image: minio/minio
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    volumes:
      - ./tmp/minio/data:/export
      - ./tmp/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
    command: server /export --console-address ":9001"
networks:
  default: {}
