services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    working_dir: /app
    tty: true
    volumes:
      - source: ./backend
        target: /app
        type: bind
    ports:
      - "8080:8080"
    environment:
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DATABASE: mucaron
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_SSLMODE: disable
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
      REDIS_HOST: redis
      REDIS_PASSWORD: "redispassword"
    depends_on:
      - postgres
      - minio
      - redis
  frontend:
    image: node:20
    working_dir: /app
    command: >
      bash -c "npm install && npm run dev"
    volumes:
      - source: ./frontend
        target: /app
        type: bind
    ports:
      - "3000:3000"
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./psql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
    command: server /export --console-address ":9001"
  redis:
    image: bitnami/redis:7.4
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redispassword"
    volumes:
      - redis_data:/bitnami/redis/data
networks:
  default: {}

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  minio_config:
    driver: local
  redis_data:
    driver: local
