name: Backend Test
on:
  pull_request:
    paths:
      - ".github/workflows/backend-test.yaml"
      - "backend/**"
  push:
    paths:
      - ".github/workflows/backend-test.yaml"
      - "backend/**"
  workflow_dispatch:

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: go.sum

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: go mod download
        run: go mod download

      - name: Run tests
        run: go test -cover ./... -coverprofile="cover.out"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          fail_ci_if_error: true
          verbose: true
