name: Back Image Build
on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: go.sum

      - name: Run tests
        run: go test -cover ./... -coverprofile="cover.out"

      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build Docker Image
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          file: Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # build-args: TARGETARCH=amd64,TARGETOS=linux
          tags: |
            ghcr.io/walnuts1018/mucaron-backend:latest
            ghcr.io/walnuts1018/mucaron-backend:${{ github.sha }}-${{ github.run_number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.25.0
        with:
          image-ref: "ghcr.io/walnuts1018/mucaron-backend:${{ github.sha }}-${{ github.run_number }}"
          format: "sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-results-backend.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-backend.sarif"
