name: Frontend Docker
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/frontend-docker.yaml"
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Cache node_modules, .next/cache, .npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next
            .npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: frontend
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/walnuts1018/mucaron-frontend:latest
            ghcr.io/walnuts1018/mucaron-frontend:${{ github.sha }}-${{ github.run_number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "ghcr.io/walnuts1018/mucaron-frontend:${{ github.sha }}-${{ github.run_number }}"
          format: "sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-results-front.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-front.sarif"
