// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/walnuts1018/mucaron/apiserver/router"
	"github.com/walnuts1018/mucaron/apiserver/router/handler"
	"github.com/walnuts1018/mucaron/apiserver/usecase"
	"github.com/walnuts1018/mucaron/common/config"
	"github.com/walnuts1018/mucaron/common/infra/postgres"
)

// Injectors from wire.go:

func CreateRouter(cfg config.Config) (*gin.Engine, error) {
	postgresClient, err := postgres.NewPostgres(cfg)
	if err != nil {
		return nil, err
	}
	usecaseUsecase := usecase.NewUsecase(postgresClient, postgresClient, postgresClient, postgresClient, postgresClient, postgresClient)
	handlerHandler, err := handler.NewHandler(cfg, usecaseUsecase)
	if err != nil {
		return nil, err
	}
	engine, err := router.NewRouter(cfg, handlerHandler)
	if err != nil {
		return nil, err
	}
	return engine, nil
}
